---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    commit-message:
      prefix: deps
    labels: [dependencies]
    # Ensure dependabot runs uv lock after updating dependencies
    # This keeps uv.lock in sync with pyproject.toml
    reviewers: []
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels: [dependencies, ci]
