name-template: v$NEXT_PATCH_VERSION
prerelease: false
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
  - title: 🛠️ Maintenance
    labels:
      - chore
      - dependencies
      - documentation
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: ""
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
