repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        name: ruff-isort
        args: [--fix, --select, I]
        stages: [commit, push]
      - id: ruff
        args: [--fix]
        stages: [commit, push]
      - id: ruff-format
        stages: [commit, push]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.3
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-PyYAML
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.2
    hooks:
      - id: pip-audit
        # pip 25.2 is the latest release and ships with
        # GHSA-4xh5-x5gv-qwph; ignore until upstream publishes a
        # patched wheel so the audit stays actionable.
        args:
          - --strict
          - --ignore-vuln
          - GHSA-4xh5-x5gv-qwph
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c, .trunk/configs/.yamllint.yaml]
  - repo: local
    hooks:
      - id: hephaestus-cleanup
        name: Hephaestus macOS cleanup
        entry: uv run hephaestus cleanup
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit, push]
      - id: lint-nested-decorators
        name: Check for nested Typer decorators
        entry: python3 scripts/lint_nested_decorators.py
        language: system
        types: [python]
        pass_filenames: true
