---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        name: ruff-isort
        args: [--fix, --select, I]
        stages: [pre-commit, pre-push]
      - id: ruff
        args: [--fix]
        stages: [pre-commit, pre-push]
      - id: ruff-format
        stages: [pre-commit, pre-push]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        pass_filenames: false
        args: [--config-file=pyproject.toml, src, tests]
        additional_dependencies:
          - pydantic
          - types-PyYAML
          - typer>=0.19.2
          - rich>=14.1.0
          - pytest>=8.4.2
          - pytest-asyncio>=1.2.0
          - httpx>=0.28.1
          - prometheus-client>=0.20.0
          - cryptography>=46.0.2
          - fastapi>=0.118.2
          - starlette>=0.48.0
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        # pip 25.2 is the latest release and ships with
        # GHSA-4xh5-x5gv-qwph; ignore until upstream publishes a
        # patched wheel so the audit stays actionable.
        args:
          - --strict
          - --ignore-vuln
          - GHSA-4xh5-x5gv-qwph
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c, .trunk/configs/.yamllint.yaml]
  - repo: local
    hooks:
      - id: hephaestus-cleanup
        name: Hephaestus macOS cleanup
        entry: uv run hephaestus cleanup
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
      - id: lint-nested-decorators
        name: Check for nested Typer decorators
        entry: python3 scripts/lint_nested_decorators.py
        language: system
        types: [python]
        pass_filenames: true
