repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-PyYAML
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        # pip 25.2 is the latest release and ships with GHSA-4xh5-x5gv-qwph; ignore until
        # upstream publishes a patched wheel so the audit stays actionable.
        args:
          - --strict
          - --ignore-vuln
          - GHSA-4xh5-x5gv-qwph
  - repo: local
    hooks:
      - id: hephaestus-cleanup
        name: Hephaestus macOS cleanup
        entry: uv run hephaestus cleanup
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit, push]
