---
site_name: Hephaestus Toolkit
site_description: Documentation for the Hephaestus developer experience toolkit
site_url: https://hephaestus.example.com
repo_url: https://github.com/IAmJonoBo/Hephaestus
repo_name: Hephaestus
nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
  - How-to guides:
      - Install from a Wheelhouse: how-to/install-wheelhouse.md
      - Configure Your Editor: how-to/editor-setup.md
      - Operating Safely: how-to/operating-safely.md
      - Quality Gate Validation: how-to/quality-gates.md
      - AI Agent Integration: how-to/ai-agent-integration.md
      - Release Process: how-to/release-process.md
      - Testing Guide: how-to/testing.md
      - Troubleshooting: how-to/troubleshooting.md
  - Explanation:
      - Architecture Overview: explanation/architecture.md
      - Evergreen Lifecycle Playbook: lifecycle.md
      - Frontier Standards Charter: explanation/frontier-standards.md
      - Frontier Red Team & Gap Analysis: >-
          explanation/frontier-red-team-gap-analysis.md
  - Reference:
      - CLI Reference: reference/cli.md
      - Telemetry Events: reference/telemetry-events.md
      - CLI Autocompletion: cli-completions.md
      - Pre-Release Checklist: pre-release-checklist.md
      - Refactoring Toolkit Map: refactoring-toolkit.md
  - Appendix:
      - ADR Template: adr/0000-template.md
      - ADR 0001 - STRIDE Threat Model: adr/0001-stride-threat-model.md
      - ADR 0002 - Plugin Architecture: adr/0002-plugin-architecture.md
      - ADR 0003 - OpenTelemetry Integration: adr/0003-opentelemetry-integration.md
      - ADR 0004 - REST/gRPC API: adr/0004-rest-grpc-api.md
      - ADR 0005 - PyPI Publication: adr/0005-pypi-publication.md
      - ADR 0006 - Sigstore Backfill: adr/0006-sigstore-backfill.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IAmJonoBo/Hephaestus
watch:
  - docs
  - README.md
