name: CI

# Minimal test pipeline that syncs via uv.lock and runs pytest with dev/qa extras.
# For uv + GitHub Actions docs (setup, caching, private indexes):
# https://github.com/astral-sh/uv/tree/main/projects/setup-uv

on: [push, pull_request]

jobs:
  deps-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install uv + requested Python with built-in caching on GH-hosted runners.
      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true # persist uv's cache across runs

      # Optional: manual cache keyed to the lockfile (uncomment to take explicit control).
      # - name: Restore uv cache (keyed to uv.lock)
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/uv
      #     key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
      #     restore-keys: |
      #       uv-${{ runner.os }}

      # Repo ships a uv.lock and installs extras exactly via `uv sync --extra dev --extra qa`.
      - name: Sync dependencies (locked)
        run: uv sync --locked --extra dev --extra qa

      # Quick smoke-check of the environment after sync.
      - name: Environment report
        run: |
          uv --version
          python -V
          uv run python -c "import sys, pkgutil; print('site:', sys.executable); print('packages:', len(list(pkgutil.iter_modules())))"

      # Run the pytest suite (available via dev extras).
      - name: Run tests
        run: uv run pytest -q

    # Private index example (commented; configure [tool.uv.index] + secrets when needed).
    # env:
    #   UV_INDEX_URL: https://pypi.org/simple  # example override
    #   UV_INDEX_INTERNAL_PROXY_USERNAME: ${{ secrets.PRIVATE_INDEX_USER }}
    #   UV_INDEX_INTERNAL_PROXY_PASSWORD: ${{ secrets.PRIVATE_INDEX_PASS }}
