name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies (qa + dev extras)
        run: uv sync --extra qa --extra dev

      - name: Scrub Apple cruft
        run: uv run hephaestus cleanup

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Static typing (mypy)
        run: uv run mypy src tests hephaestus-toolkit/refactoring/scripts

      - name: Run test suite with coverage
        run: uv run pytest

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Security audit (pip-audit)
        if: matrix.python-version == '3.13'
        run: uv run pip-audit --strict --ignore-vuln GHSA-4xh5-x5gv-qwph
        # pip 25.2 currently ships with GHSA-4xh5-x5gv-qwph and no patched release;
        # ignore until upstream publishes a fix to keep the audit actionable.
