---
name: dependency-review

"on":
  pull_request:

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Dependency review
        uses: actions/dependency-review-action@v4
