---
name: macOS Metadata Guard

'on':
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions: read-all

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Verify workspace is free of macOS artefacts
        run: |
          set -euo pipefail
          pattern='(^|/)(\.DS_Store|\.Apple(Double|Desktop|DB)|'
          pattern+='\.DocumentRevisions-V100|\.LSOverride|'
          pattern+='\.Spotlight-V100|\.Trashes|\.fseventsd|'
          pattern+='\.TemporaryItems|\.apdisk|\._[^/]+)$'
          offending=$(git ls-files --cached --others \
            --exclude-standard | grep -E "$pattern" || true)
          if [ -n "$offending" ]; then
            echo "Found macOS metadata files in repository history " \
              "or working tree:"
            echo "$offending"
            exit 1
          fi
          echo "No macOS metadata detected."
