name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for PyPI Trusted Publishers
  contents: write

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    # environment block removed due to invalid value

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine sigstore

      - name: Build distribution
        run: python -m build

      - name: Sign with Sigstore
        run: |
          python -m sigstore sign dist/*

      - name: Verify distribution
        run: |
          twine check dist/*

      - name: Publish to Test PyPI (pre-releases)
        if: github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI (stable)
        if: ${{ github.event.release.prerelease == false }}
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Attach Sigstore bundles to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.sigstore
          asset_name: sigstore-bundles.tar.gz
          asset_content_type: application/gzip
