name: Sigstore Bundle Backfill

# Workflow for backfilling Sigstore bundles on historical releases (ADR-0006)
# This is a manually triggered workflow to avoid accidental execution

on:
  workflow_dispatch:

permissions:
  contents: write # Required to upload release assets and update notes
  id-token: write # Required for Sigstore OIDC authentication

jobs:
  backfill:
    name: Backfill Sigstore Bundles
    runs-on: ubuntu-latest
    # environment block removed because 'backfill' is not a valid environment name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sigstore requests

      - name: Run backfill script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running LIVE backfill"
          python scripts/backfill_sigstore_bundles.py

      - name: Comment on completion
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `✅ Sigstore backfill completed.\n\n` +
                `See [workflow run](${context.serverUrl}/` +
                `${context.repo.owner}/${context.repo.repo}/` +
                `actions/runs/${context.runId}) for details.`
            });
